#!/bin/bash
# .git/hooks/post-checkout


# First dump migrations that have been applied on this branch.
if [ -z $STAGE ]
then
    python -m django_nomad dump
    export STAGE=start
    git checkout --quiet -
elif [ ! -z $STAGE ] && [ $STAGE == "start" ]
then
    TARGETS=`python -m django_nomad find_targets`
    while IFS= read -r target; do
        python manage.py migrate $target
    done <<< "$TARGETS"
    export STAGE=second
    git checkout --quiet -
elif [ ! -z $STAGE ] && [ $STAGE == "second" ]
then
    python manage.py migrate
    unset STAGE
fi
