#!/bin/bash
# .git/hooks/post-checkout

# Post checkout receives previous HEAD, current HEAD and a flag that 
# indicates if the checkout is branch or file.
is_branch_checkout=$3

if [ "$is_branch_checkout" == "1" ]; then
    .venv/bin/python -m django_nomad migrate
fi
