name: Tag

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-tags: true
    - name: Push New Tag.
      run: |
        VERSION=v$(sed -nr "s/^version.*=.*\"([[:digit:]]+.[[:digit:]]+.[[:digit:]]+)\"/\1/p" pyproject.toml)
        git tag $VERSION
        tag_exists=$?
        if [[ tag_exists ]]; 
        then echo "Tag already exists."
        else git push --tags
        fi
