# This workflow will install Python dependencies,
# run tests and lint with a variety of Python versions
# For more information see:
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v3
      with:
        python-version: 3.x
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 coverage
        python -m pip install --editable .
    - name: Lint
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test
      env:
        GH_TOKEN: ${{ secrets.GIST_TOKEN }}
      run: |
        coverage run -m --omit="tests/*" unittest discover
        coverage report --show-missing
        # Generate json data to be placed in gist.
        coverage json -o django-nomad_coverage.json

        # Update the public gist so that the README.md refects results.
        # NB this gist has to already exist!
        gist_id=$(gh gist list --public | sed -nE "s/^(\w+)\s+django-nomad_coverage.json.*/\1/p")
        gh gist edit $gist_id --remove django-nomad_coverage.json
        gh gist edit $gist_id --add django-nomad_coverage.json