# This workflow will install Python dependencies,
# run tests and lint with a variety of Python versions
# For more information see:
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      isNewTag: ${{ steps.versionCheck.outputs.isNewTag }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v3
      with:
        python-version: 3.x
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 coverage
        python -m pip install --editable .
    - name: Lint
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test
      env:
        GH_TOKEN: ${{ secrets.GIST_TOKEN }}
      run: |
        coverage run -m --omit="tests/*" unittest discover
        coverage report --show-missing
        # Generate json data to be placed in gist.
        coverage json -o django-migrant_coverage.json

        # Update the public gist so that the README.md refects results.
        # NB this gist has to already exist!
        gist_id=$(gh gist list --public | sed -nE "s/^(\w+)\s+django-migrant_coverage.json.*/\1/p")
        if [[ gist_id ]]; 
        then
          gh gist edit $gist_id --remove django-migrant_coverage.json
          gh gist edit $gist_id --add django-migrant_coverage.json
        else
          gh gist create --public --desc django-migrant_coverage.json django-migrant_coverage.json
        fi
    - name: Check If Version Is New
      id: versionCheck
      run: |
        VERSION=v$(sed -nr "s/^version.*=.*\"([[:digit:]]+.[[:digit:]]+.[[:digit:]]+)\"/\1/p" pyproject.toml)
        git fetch --tags
        exists=$(git tag --list $VERSION)
        if [[ $exists ]]; 
        then echo "isNewTag=false" >>$GITHUB_OUTPUT
        else echo "isNewTag=true" >>$GITHUB_OUTPUT
        fi
  publish-to-testpypi:
    needs: test
    if: needs.test.outputs.isNewTag == 'true'
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/django-migrant
    permissions:
      id-token: write
    steps:
      - name: Download Package
        uses: actions/download-artifact@v4
        with:
          name: package-files
          path: dist/
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
  publish-to-pypi:
    needs: publish-to-testpypi
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/django-migrant
    permissions:
      id-token: write
    steps:
      - name: Download Package
        uses: actions/download-artifact@v4
        with:
          name: package-files
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
  tag:
    needs: publish-to-pypi
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Tag
      run: |
        VERSION=v$(sed -nr "s/^version.*=.*\"([[:digit:]]+.[[:digit:]]+.[[:digit:]]+)\"/\1/p" pyproject.toml)
        git tag $VERSION
        git push --tags
